In [1]:
import numpy as np

In [2]:
True or False

True

In [3]:
True and False

False

In [4]:
not True

False

In [6]:
True ^ False

True

In [7]:
5 == 6

False

In [3]:
array1 = [True, True, False, False, True]
array2 = [True, False, False, True, False]

In [4]:
np.logical_and(array1, array2)

array([ True, False, False, False, False])

In [6]:
np.logical_not(array1)

array([False, False,  True,  True, False])

In [7]:
np.logical_or(array1, array2)

array([ True,  True, False,  True,  True])

In [8]:
np.logical_xor(array1, array2)

array([False,  True, False,  True,  True])