In [1]:
import numpy as np

In [4]:
one_d = np.array([1, 2, 3, 4, 5])
one_d

array([1, 2, 3, 4, 5])

In [6]:
two_d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
two_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
[np.random.randint(1, 10) for i in range(5)]

[8, 5, 1, 5, 9]

In [40]:
x = np.arange(25).reshape((5,5)) + 1
np.diag(np.diag(x))

array([[ 1,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 19,  0],
       [ 0,  0,  0,  0, 25]])