In [2]:
import numpy as np

In [4]:
m = np.arange(9).reshape((3, 3))
mat = np.array([[10, 11, 12], [13, 14, 15]])

print("Matrix 1 is: \n", m)
print("\nMatrix 2 is: \n", mat)

Matrix 1 is: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix 2 is: 
 [[10 11 12]
 [13 14 15]]


In [5]:
2 + m

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
10 - m

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [7]:
7 * m

array([[ 0,  7, 14],
       [21, 28, 35],
       [42, 49, 56]])

In [9]:
np.matmul(m, mat.T)

array([[ 35,  44],
       [134, 170],
       [233, 296]])

In [11]:
# Row 2, all Columns
m[1, :]

array([3, 4, 5])

In [12]:
# All Row 2, Column 2
m[:, 1]

array([1, 4, 7])